### ISSUE TITLE
No events to my mqtt client

### ISSUE THREAD

**Issue by stefanobimbo** [gotthardp/lorawan-server#586]
I use 0.6.4
I configured an MQTT connector as follows:

![immagine](https://user-images.githubusercontent.com/31661872/51667515-983fa300-1fc0-11e9-816e-888aa06c799c.png)

I can see uplink messages in my mqtt subscriber  and send downlink message from my mqtt publisher. Downlink messages arrive to my end node, so I'm shure both uplink and downlink topics work OK.
The problem is that I don't receive events on "ClasseC/events" topic.
I aspect to receive event messages when my confirmed dowlink message is either delivered or lost.

**Comment by amc2505** [comment]
I  have the same issue.. uplink is ok with mqtt but not events

**Comment by gotthardp** [comment]
That is weird. It shall work as you said. Any warning/error in the server log?

**Comment by amc2505** [comment]
Hello,

Nothings in the logs….

Thks.


De : Petr Gotthard <notifications@github.com>
Répondre à : gotthardp/lorawan-server <reply@reply.github.com>
Date : mardi 29 janvier 2019 à 21:48
À : gotthardp/lorawan-server <lorawan-server@noreply.github.com>
Cc : Alain-michel CIETERS <am.cieters@noolitic.com>, Comment <comment@noreply.github.com>
Objet : Re: [gotthardp/lorawan-server] No events to my mqtt client (#586)


That is weird. It shall work as you said. Any warning/error in the server log?

**Comment by gotthardp** [comment]
Oh, that is indeed a bug. I made a fix. Would you be able to build the server from sources and test it, please? Or you want to wait for a release?

**Comment by amc2505** [comment]
I can wait for the next release. but i'm not alone.

thks.

regards

**Comment by moneybag** [comment]
same problem here, using mosquitto

**Comment by gotthardp** [comment]
@moneybag, and can you test the latest MASTER, please? it should be fixed there

**Comment by gotthardp** [comment]
Fixed in v0.6.5

**Comment by amc2505** [comment]
Hi,

When will you build a new release ?

Thks.

De : Petr Gotthard <notifications@github.com>
Répondre à : gotthardp/lorawan-server <reply@reply.github.com>
Date : mercredi 13 février 2019 à 10:47
À : gotthardp/lorawan-server <lorawan-server@noreply.github.com>
Cc : Alain-michel CIETERS <am.cieters@noolitic.com>, Comment <comment@noreply.github.com>
Objet : Re: [gotthardp/lorawan-server] No events to my mqtt client (#586)


Closed #586<https://github.com/gotthardp/lorawan-server/issues/586>.

**Comment by gotthardp** [comment]
I just did.

**Comment by amc2505** [comment]
Thks.

De : Petr Gotthard <notifications@github.com>
Répondre à : gotthardp/lorawan-server <reply@reply.github.com>
Date : mercredi 13 février 2019 à 10:58
À : gotthardp/lorawan-server <lorawan-server@noreply.github.com>
Cc : Alain-michel CIETERS <am.cieters@noolitic.com>, Comment <comment@noreply.github.com>
Objet : Re: [gotthardp/lorawan-server] No events to my mqtt client (#586)


I just did.

**Comment by romansoft** [comment]
I'm still seeing this issue in 0.6.7. Has it not been pushed yet?
